### ISSUE TITLE
Sidecar mode - write access rules to file

### ISSUE THREAD

**Issue by piotrmsc** [ory/oathkeeper-maester#21]
## Description

We should be able to run controller in the sidecar mode, saving provided access rules to file. In this mode controller is running as a second container in the pod.

Current workflow with integration via configmap works but is slow (refresh time). 
Mode should be enabled via config and it should be a generic implementation : interface with different implementations (one for configmap one for file)

AC :
- Writing to file/cm enabled in the config. Writing to file by default
- Writing to file/cm implemented in a generic way (interface with different impl)
- Tests
- Document all available flags in README
- Update charts (make this change optional, enabled via value, default behavior is configmap)

Probably leader election should be disabled in such scenario, all controllers should react on CRs.

**Comment by aeneasr** [comment]
Looks like it was referenced and merged!
