### ISSUE TITLE
Error handlers & matches not supported

### ISSUE THREAD

**Issue by piotrmsc** [ory/oathkeeper-maester#41]
### Description

Oathkeeper supports [error handlers](https://www.ory.sh/oathkeeper/docs/pipeline/error) with for example redirect. This property is not supported in the controller but for some users this feature is desired. The same goes with [error matches ](https://www.ory.sh/oathkeeper/docs/pipeline/error#error-matching)

Rule Spec does not have those properties https://github.com/ory/oathkeeper-maester/blob/master/api/v1alpha1/rule_types.go#L59 and CRD needs to be updated as well.

**Comment by aeneasr** [comment]
Nice! Please keep in mind that we want to refactor the config a bit...

https://github.com/ory/oathkeeper/issues/441
