### ISSUE TITLE
Provide ARM Docker Image

### ISSUE THREAD

**Issue by yoo** [ory/oathkeeper-maester#68]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper-maester/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper-maester/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I try to deploy the [oathkeeper helm chart](https://github.com/ory/k8s/tree/master/helm/charts/oathkeeper)  to a Kubernetes cluster running on `arm64` hardware. The `oathkeeper-maester` pod fails with: `exec /manager: exec format error`. The  [docker image](https://hub.docker.com/r/oryd/oathkeeper-maester/tags) only supports `amd64`. 

### Describe your ideal solution

The other ory docker images are built for arm.  It would be nice if oathkeeper-maester would support arm docker images too.

### Workarounds or alternatives

I have removed the `GOARCH` from the `Makefile` and build a arm version of the image with:
```
docker buildx build --platform=linux/arm64 --tag ghcr.io/yoo/oathkeeper-maester:latest --push .
```

You can try the image yourself. https://github.com/users/yoo/packages/container/package/oathkeeper-maester

### Version

0.1.7

**Comment by 0xfourzerofour** [comment]
I am also wanting the arm docker image, I could always do the same thing as   @yoo
